variable "ec2_name" {
  type = string
}

variable "instance_type" {
  type = string
}

variable "ami_id" {
  type = string
}

variable "subnet_id" {
  type = string
}

variable "security_group_ids" {
  type = list(string)
}

variable "user_data" {
  type = string
  default = <<EOF
#!/bin/bash
sudo apt update -y
sudo apt install apache2 -y
sudo systemctl start apache2
sudo systemctl enable apache2
echo "<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello from terraform</title>
</head>
<body>
    <div>
        <h1>Hello from terraform</h1>
        <p>This is a simple HTML page generated by Terraform.</p>
        <i style="color: #ca0f0f;">made by Aadityasinh Zala</i>
    </div>
</body>
</html>" > /var/www/html/index.html
EOF
}